### ISSUE TITLE
petition: use pnpm

### ISSUE THREAD

**Issue by aidenybai** [melindachang/cca-birding#1]
yarn??? disgusting

peeporiot!!!
![image](https://user-images.githubusercontent.com/38025074/133916231-61d9261b-7a94-4f39-8ce8-3876bfac175b.png)

**Comment by melindachang** [comment]
![image](https://user-images.githubusercontent.com/32805643/133917424-4cb89017-7a5d-4407-8521-ce189952fb30.png)

**Comment by aidenybai** [comment]
![image](https://user-images.githubusercontent.com/38025074/133917686-89bc6735-fab8-4beb-8afb-c576aa5a2602.png)
